export default jsonData = {
    questions: [
      "You prefer to go out and talk a lot to strangers and your friends and can be considered open about yourself",
      "You like to work under pressure and always go the extra mile",
      "You think well in a group with support from your peers/ You think of ideas better when you're alone",
      "You strive to be the centre of conversation when you try to walk into a room",
      "People usually observe you while you're talking in a social outing",
      "You like to run the show",
      "You describe yourself as a realist rather than a dreamer",
      "You pay attention to the concrete details and prefer a more in-depth view rather than a bird's eye view",
      "You like practical ideas with real applications rather than abstract concepts or hypotheticals",
      "You concentrate on the specifics while describing something rather than being figurative",
      "You find yourself worrying about the correct facts frequently",
      "You make decisions based on logic rather than emotions",
      "You value justice over mercy",
      "You enjoy winning an argument by finding flaws in others rather than losing it",
      "Your peers and relatives often describe you as a mature and level-headed person",
      "You're more focused on being fair rather than being empathetic",
      "You prefer to have a plan rather than looking out and waiting for what happens in the future",
      "Rules are important to you and you respect deadlines",
      "You prefer being well-informed with instructions rather than improvising on the go",
      "You prefer to have all the details before making a decisions rather than being spontaneous",
      "You have your whole life planned out",
    ],
    category:[
      "EI","EI","EI","EI","EI","EI",
      "SN","SN","SN","SN","SN",
      "TF","TF","TF","TF","TF",
      "JP","JP","JP","JP","JP",
    ],
    options: [
      "Strongly agree",
      "Agree",
      "Neutral",
      "Disagree",
      "Strongly disagree"
    ],
    scoring : [
      1.5,
      1,
      0,
      -1,
      -1.5,
    ]
  }